name: ope_pid
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pip
  - pip:
      - ninja
      - pycocotools
      - detectron2@git+https://github.com/facebookresearch/detectron2.git
      - opencv-python
      - numpy
      - matplotlib
      - pyyaml
      - tqdm